import type { Metadata } from "next";
import { Inter } from "next/font/google";
import IntlProvider from "@/components/IntlProvider"; // Import the IntlProvider
import Dropdown from "@/components/dropdown";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <head>
        <title>Your App Title</title>
        <meta name="description" content="Your app description" />
      </head>
      <body className={inter.className}>
        <IntlProvider locale={locale}>
          <div className="flex flex-col min-h-screen">
            <header className="bg-gray-900 mb-8 py-4 text-white">
              <div className="container mx-auto flex justify-between items-center">
                <a href="/" className="text-white text-2xl font-bold">
                  Home
                </a>
                <span className="mx-auto">Tailwind CSS Blog</span>
                <Dropdown /> {/* Language Switcher */}
              </div>
            </header>
            <main className="container mx-auto flex-1">{children}</main>
            <footer className="bg-gray-900 mt-8 py-4 text-white">
              <div className="container mx-auto flex justify-center">
                &copy; 2024 Kanika Bhatt
              </div>
            </footer>
          </div>
        </IntlProvider>
      </body>
    </html>
  );
}
